### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder' when running pacific test

### ISSUE THREAD

**Issue by skurscheid** [pacific-2020/pacific#7]
HI there!

I saw your preprint a few days ago, and wanted to test installation of some ML libraries on the local cluster anyway so I thought it would a good opportunity to test your classifier.

I think that I installed all the requirements in a separate conda environment (see below) and it is properly isolated from all other environment variables. However when trying to run pacific as described in the README i get following error:

```bash
(pacific) [kursch0000@shi03 test]$ python ../PACIFIC.py -i test.fa.gz -m ../model/pacific.01.pacific_9mers_nonGPU.h5 -t ../model/tokenizer.01.pacific_9mers.pickle -l ../model/label_maker.01.pacific_9mers.pickle -f fasta
Using TensorFlow backend.
Traceback (most recent call last):
  File "../PACIFIC.py", line 312, in <module>
    model = load_model(MODEL)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/sequential.py", line 301, in from_config
    model.add(layer)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/sequential.py", line 161, in add
    name=layer.name + '_input')
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/scicore/home/resit/kursch0000/miniconda3/envs/pacific/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'
``` 
Any ideas what could be causing this? 

My conda environment:
```bash
(pacific) [kursch0000@shi03 pacific]$ conda env export
name: pacific
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=0.10.0=py37hc8dfbb8_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=py_0
  - binutils_impl_linux-64=2.35=h18a2f87_9
  - binutils_linux-64=2.35=heab0d09_28
  - biopython=1.78=py37h8f50634_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h516909a_1000
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.7.22=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37hc8dfbb8_1007
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.1=py37hb09aad4_0
  - gast=0.3.3=py_0
  - gcc_impl_linux-64=7.5.0=hdb87b24_16
  - gcc_linux-64=7.5.0=hf34d7eb_28
  - google-auth=1.21.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.31.0=py37hb0870dc_0
  - gxx_impl_linux-64=7.5.0=h1104b78_16
  - gxx_linux-64=7.5.0=ha781d05_28
  - h5py=2.10.0=nompi_py37h90cd8ad_104
  - hdf5=1.10.6=nompi_h3c11f04_101
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py37hc8dfbb8_0
  - joblib=0.16.0=py_0
  - keras=2.2.4=py37_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.3=he6710b0_2
  - libgcc-devel_linux-64=7.5.0=h42c25f5_16
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libgpuarray=0.7.6=h14c3975_1003
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libprotobuf=3.13.0=h8b12597_0
  - libstdcxx-devel_linux-64=7.5.0=h4084dd6_16
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - mako=1.1.3=pyh9f0ad1d_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37h8f50634_1
  - ncurses=6.2=he1b5a44_1
  - numpy=1.19.1=py37h7ea13bd_2
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1h=h516909a_0
  - opt_einsum=3.3.0=py_0
  - pandas=0.25.1=py37hb3f55d8_0
  - pip=20.2.3=py_0
  - protobuf=3.13.0=py37h3340039_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygpu=0.7.6=py37h03ebfcd_1001
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h8f50634_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.5.2=py37hb14ef9d_0
  - setuptools=49.6.0=py37hc8dfbb8_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tensorboard=2.3.0=py_0
  - tensorboard-plugin-wit=1.6.0=pyh9f0ad1d_0
  - tensorflow=2.2.0=mkl_py37h6e9ce2d_0
  - tensorflow-base=2.2.0=mkl_py37hd506778_0
  - tensorflow-estimator=2.2.0=pyh95af2a2_0
  - termcolor=1.1.0=py_2
  - theano=1.0.5=py37h3340039_0
  - tk=8.6.10=hed695b0_0
  - urllib3=1.25.10=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.12.1=py37h8f50634_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.2.0=py_0
  - zlib=1.2.11=h516909a_1009
prefix: /scicore/home/resit/kursch0000/miniconda3/envs/pacific
```

**Comment by hp2048** [comment]
Hi @skurscheid : It seems to be version issues for some libraries. I have tested the following and it works on my computer. Could you please try the following and let us know if it works? If it does, then I will update the README file.
```
conda create --name testpacific python=3.7.6
conda activate testpacific
conda install numpy=1.18.1 tensorflow=2.2.0 keras=2.3.1 pandas=1.0.1 scikit-learn=0.21.3 biopython=1.76
git clone https://github.com/pacific-2020/pacific.git
cd pacific
wget -O model/pacific.01.pacific_9mers_nonGPU.h5 https://cloudstor.aarnet.edu.au/plus/s/Hwg20YRlua9a2OH/download
python ../PACIFIC.py -i test.fa.gz -m ../model/pacific.01.pacific_9mers_nonGPU.h5 -t ../model/tokenizer.01.pacific_9mers.pickle -l ../model/label_maker.01.pacific_9mers.pickle -f fasta
```
Thank you for trying this and pointing out the bug.
Cheers
Hardip

**Comment by skurscheid** [comment]
Hi @hp2048,

thanks for that - this fixed the error and I was able to successfully run the test

Cheers,

Sebastian
